"dutch corona":
  - "corona"
  - "covid"
  - "virus"
  - "omt"
  - "rivm"
  - "gommers"
  - "avondklok"
  - "viruswaarheid"
  - "viruswaanzin"
"dutch politiek":
  - "overheid"
  - "landelijk"
  - "gemeente"
  - "provincie"
  - "minszw"
  - "minvws"
  - "minalg"
  - "minbuza"
  - "mindef"
  - "minfin"
  - "minpres"
  - "wimlex"
  - "regering"
  - "politiek"
  - "minister"
  - "president"
  - "koning"
  - "maxima"
  - "koningin"
  - "pvv"
  - "vvd"
  - "groenlinks"
  - "d66"
  - "cda"